apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: metadata-service
  labels:
    app: metadata-service-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: metadata-service-app
  template:
    metadata:
      labels:
        app: metadata-service-app
    spec:
      containers:
      - image: saffya/metadata-service
        name: metadata-service-container
        ports:
        - containerPort: 8080
          protocol: TCP
