apiVersion: v1
kind: Service
metadata:
  name: service-external-metadata-service
spec:
  type: NodePort
  selector:
    app: metadata-service-app
  ports:
    - port: 90
      targetPort: 8080
      nodePort: 30007
